name: Deploy with Secrets

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace secrets in code
        run: |
          sed -i "s/YOUR_STRAVA_CLIENT_ID/${{ secrets.STRAVA_CLIENT_ID }}/g" strava-integration.js
          sed -i "s/YOUR_STRAVA_CLIENT_SECRET/${{ secrets.STRAVA_CLIENT_SECRET }}/g" strava-integration.js
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
