name: Get Strava Refresh Token

on:
  workflow_dispatch:

jobs:
  fetch-refresh-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Show exactly which workflow file the runner is using
      - name: Show workflow file (sanity check)
        run: |
          echo "=== WORKFLOW FILE CONTENTS ==="
          cat .github/workflows/get-refresh-token.yml || true
          echo "=============================="

      # Light-weight debug without multiline YAML
      - run: pwd
      - run: echo "Repo root:" && ls -la
      - run: echo "Full repo tree:" && ls -R .

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run refresh token script
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_CODE: ${{ secrets.YOUR_AUTHORIZATION_CODE }}   # your one-time code secret
        run: node .github/scripts/fetch-refresh-token.js        # matches your repo layout


